# Generated by Django 4.2 on 2023-04-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nome',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
