# Generated by Django 4.2 on 2023-04-15 03:31

import django.core.validators
from django.db import migrations, models

#Adicionando filmes ao banco de dados
class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_alter_perfil_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Genero', models.CharField(max_length=100)),
                ('Elenco', models.CharField(max_length=500)),
                ('Sinopse', models.TextField(max_length=1000)),
                ('Avaliacao', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('Capa', models.CharField(max_length=100)),
                ('Ano_de_producao', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('Views_count', models.IntegerField(default=0)),
            ],
        ),
    ]
