# Generated by Django 4.2 on 2023-04-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_alter_perfil_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('elenco', models.CharField(max_length=100)),
                ('sinopse', models.TextField(max_length=1000)),
                ('capa', models.CharField(max_length=100)),
                ('ano_de_producao', models.DateField()),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
    ]
