# Generated by Django 4.2 on 2023-04-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_filme_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='capa',
            field=models.ImageField(upload_to='capas_movie'),
        ),
    ]
