# Generated by Django 4.2 on 2023-04-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_filme_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='status',
            field=models.CharField(blank=True, choices=[('WATCHLIST', 'Watchlist'), ('ASSISTIDO', 'Assistido'), ('FAVORITO', 'Favorito')], max_length=100),
        ),
    ]
