# Generated by Django 4.2 on 2023-05-10 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galeria', '0007_filme_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Favoritado', 'Favoritado'), ('Desfavoritdao', 'Desfavoritdao')], default='Favourite', max_length=15)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galeria.filme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
