# Generated by Django 4.2 on 2023-05-10 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_alter_filme_favourites_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
