# Generated by Django 4.2 on 2023-05-10 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galeria', '0009_delete_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='watchlists',
            field=models.ManyToManyField(blank=True, related_name='watchlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
