# Generated by Django 4.2 on 2023-05-10 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0010_filme_watchlists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField(null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galeria.filme')),
            ],
        ),
    ]
