# Generated by Django 4.2 on 2023-05-10 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0011_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='galeria.filme'),
        ),
    ]
