# Generated by Django 4.2 on 2023-05-10 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0012_alter_comment_filme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='body',
        ),
    ]
