# Generated by Django 4.2 on 2023-05-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0014_filme_estrelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='estrelas',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
